---
- hosts: all
  vars:
    image: openjdk:latest
    container_name: java_container
  tasks:

  - name: Make the base image available locally
    docker_image:
        name: '{{image}}'

  - name: Create file if it not exist 
    file:
      path: ~/workspace
      state: directory
      mode: 0755

  - name: Create the container
    docker_container:
        image: '{{image}}'
        name: '{{container_name}}'
        state: started        
        ports:
         - "8080:9000"
        volumes:
         - "~/workspace:/home/toan/workspace"

  - name : copy file to remote hosts
    copy:
      src: ./target/demojenkins-0.0.1-SNAPSHOT.jar
      dest: /home/toan/workspace/demojenkins-0.0.1-SNAPSHOT.jar