---
- hosts: api
  vars:
    image: openjdk
    container_name: java_container
  tasks:
  - name : Copy file to remote hosts
    copy:
      src: ./archive
      dest: /home/$(whoami)/workspace

  - name : Copy file to remote hosts
    copy:
      src: ./target/demojenkins-0.0.1-SNAPSHOT.jar
      dest: /home/toan/workspace/demojenkins-0.0.1-SNAPSHOT.jar