---
- hosts: api
  vars:
    image: openjdk
    container_name: java_container
  tasks:
  - name : Copy file to remote hosts - dockerfile
    copy:
      src: ./archive/dockerfile
      dest: /home/$(whoami)/workspace/dockerfile

  - name : Copy file to remote hosts - start.sh
    copy:
      src: ./archive/start.sh
      dest: /home/$(whoami)/workspace/start.sh

  - name : Copy file to remote hosts
    copy:
      src: ./target/demojenkins-0.0.1-SNAPSHOT.jar
      dest: /home/toan/workspace/demojenkins-0.0.1-SNAPSHOT.jar