#Download base image java
FROM java:openjdk-8-jdk-alpine

#Run command
RUN mkdir ~/workspace
COPY /home/toan/workspace/demojenkins-0.0.1-SNAPSHOT.jar /root/workspace/demojenkins-0.0.1-SNAPSHOT.jar
COPY /home/toan/workspace/start.sh /start.sh

CMD ["./start.sh"]
EXPOSE 8888