#Download base image java
FROM java:openjdk-8-jdk-alpine

#Run command
RUN mkdir ~/workspace
COPY ./demojenkins-0.0.1-SNAPSHOT.jar /root/workspace/demojenkins-0.0.1-SNAPSHOT.jar
COPY ./start.sh /start.sh
RUN chmod -R 777 /start.sh
RUN chmod -R 777 /root/workspace/demojenkins-0.0.1-SNAPSHOT.jar

CMD ["./start.sh"]
EXPOSE 8888